In [ ]:
#Lt col yuvraj singh

In [ ]:
#24-27-01

In [ ]:
#Mtech data sc 

In [1]:
#1 (a)question : Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape. Hint : arange

In [3]:
import numpy as np

# Creating a variable var1 that stores an array of numbers from 0 to 30 inclusive
var1 = np.arange(31)

# Printing the array and its shape
print("var1:", var1)
print("Shape of var1:", var1.shape)


var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1: (31,)


In [ ]:
# 1(b)question Change var2 to a validly-shaped two-dimensional matrix and store it in a
# new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [5]:
import numpy as np

# Creating a variable var1 that stores an array of numbers from 0 to 30 inclusive
var1 = np.arange(30)

# Reshape var1 to a validly-shaped 2D matrix
var2 = var1.reshape(5, 6)  # 5 rows, 6 columns

# Print var2 and its shape
print("var2:\n", var2)
print("Shape of var2:", var2.shape)


var2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Shape of var2: (5, 6)


In [ ]:
#1(c)Create a third variable, var3 that reshapes it into a valid three-dimensional shape. Print var3 and its shape.

In [7]:
import numpy as np

# Creating a variable var1 that stores an array of numbers from 0 to 30 inclusive
var1 = np.arange(30)

# Reshape var1 to a validly-shaped 2D matrix
var2 = var1.reshape(5, 6)  # 5 rows, 6 columns

# Reshape var2 into a valid 3D matrix
var3 = var1.reshape(2, 3, 5)  # 2 blocks, 3 rows, 5 columns

# Print var3 and its shape
print("var3:\n", var3)
print("Shape of var3:", var3.shape)


var3:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Shape of var3: (2, 3, 5)


In [ ]:
#1(d)Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change? Explain what’s
#going on. (Hint: does reshape return a view or a copy?)

In [9]:
import numpy as np

# Create var1 and reshape to var2 and var3
var1 = np.arange(30)
var2 = var1.reshape(5, 6)  # 2D array: 5 rows, 6 columns
var3 = var1.reshape(2, 3, 5)  # 3D array: 2 blocks, 3 rows, 5 columns

# Modify the first value in the second row of var2
var2[1, 0] = -1  # Set the first element in the second row to -1

# Print var1, var2, and var3 after modification
print("var2 after modification:\n", var2)
print("var1 after modification:\n", var1)
print("var3 after modification:\n", var3)


var2 after modification:
 [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
var1 after modification:
 [ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
var3 after modification:
 [[[ 0  1  2  3  4]
  [ 5 -1  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [11]:
#1(e)Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:
#(i) Sum var3 over its second dimension and print the result.
#(ii) Sum var3 over its third dimension and print the result.
#(iii) Sum var3 over both its first and third dimensions and print the result.
import numpy as np

# Recreate var1 and reshape into var3
var1 = np.arange(30)
var3 = var1.reshape(2, 3, 5)  # 2 blocks, 3 rows, 5 columns

# (i) Sum var3 over its second dimension (axis=1)
sum_over_second_dim = np.sum(var3, axis=1)
print("Sum of var3 over the second dimension (axis=1):\n", sum_over_second_dim)

# (ii) Sum var3 over its third dimension (axis=2)
sum_over_third_dim = np.sum(var3, axis=2)
print("\nSum of var3 over the third dimension (axis=2):\n", sum_over_third_dim)

# (iii) Sum var3 over both its first and third dimensions (axis=(0,2))
sum_over_first_and_third_dim = np.sum(var3, axis=(0, 2))
print("\nSum of var3 over both the first and third dimensions (axis=(0,2)):\n", sum_over_first_and_third_dim)


Sum of var3 over the second dimension (axis=1):
 [[15 18 21 24 27]
 [60 63 66 69 72]]

Sum of var3 over the third dimension (axis=2):
 [[ 10  35  60]
 [ 85 110 135]]

Sum of var3 over both the first and third dimensions (axis=(0,2)):
 [ 95 145 195]


In [ ]:
#1(f)Write code to do the following:
#(i) Slice out the second row of var2 and print it.
#(ii) Slice out the last column of var2 using the -1 notation and print it. (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.


In [13]:
import numpy as np

# Create var1 and reshape to var2
var1 = np.arange(30)
var2 = var1.reshape(5, 6)  # 2D array: 5 rows, 6 columns

# (i) Slice out the second row of var2 and print it
second_row = var2[1, :]
print("Second row of var2:\n", second_row)

# (ii) Slice out the last column of var2 using the -1 notation and print it
last_column = var2[:, -1]
print("\nLast column of var2:\n", last_column)

# (iii) Slice out the top-right 2x2 submatrix of var2 and print it
top_right_submatrix = var2[:2, -2:]
print("\nTop right 2x2 submatrix of var2:\n", top_right_submatrix)


Second row of var2:
 [ 6  7  8  9 10 11]

Last column of var2:
 [ 5 11 17 23 29]

Top right 2x2 submatrix of var2:
 [[ 4  5]
 [10 11]]


In [15]:
# 2(a) question The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.
import numpy as np

# Create a vector from 0 to 9 using arange, and add 1 to each element
vector = np.arange(10) + 1

# Print the vector
print("Vector 1 to 10:\n", vector)


Vector 1 to 10:
 [ 1  2  3  4  5  6  7  8  9 10]


In [17]:
# question 2 (b)Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.
import numpy as np

# Create a vector from 1 to 10
vector = np.arange(10) + 1  # [1, 2, ..., 10]

# Create the 10x10 matrix A where A[i, j] = i + j
A = vector.reshape(10, 1) + vector  # Broadcasting the vector to create the matrix

# Print the resulting matrix A
print("Matrix A (A[i, j] = i + j):\n", A)


Matrix A (A[i, j] = i + j):
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [19]:
#A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples, each with five dimensions. import numpy.random as npr
 #data = np.exp(npr.randn ( 50 , 5 ) import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Print the resulting dataset
print("Fake dataset (50 examples, 5 dimensions):\n", data)


Fake dataset (50 examples, 5 dimensions):
 [[ 0.32903775  1.10328889  1.07528577  1.68602614  2.4703175 ]
 [ 1.46285979  6.29485531  0.25237873  5.42730671  0.57765097]
 [ 0.45356943  3.44749313  0.62568537  0.66092142  0.69571721]
 [ 1.43239567  0.64143313  0.90428228  0.88007775  0.57846883]
 [ 4.74806068  1.68719151  0.62021384  1.89609948  2.62293973]
 [ 0.13701663  1.36819801  0.67139771  3.06370333  0.72492329]
 [ 9.98155646  0.70668183  0.28889945  0.50217656  0.43938507]
 [ 0.11503669  0.32357383  0.51276839  1.08146931  0.43000294]
 [ 3.447473    2.12107502  0.56966864  0.41953976  0.60384944]
 [ 3.29605221  0.51215082  0.22384366  0.34365577  0.90831824]
 [ 0.87702985  0.75634954  3.08647333  0.31699512  0.12318024]
 [ 1.50081627  1.1934728   3.21209611  0.66769381  5.01407025]
 [ 0.28936992  2.62193228  0.27458836  0.48727274  1.66204624]
 [ 2.01070994  1.34859125  2.10927624  0.97723882  2.10644361]
 [ 0.18364848  6.19982445  0.31527378  0.63912115  0.31585231]
 [ 1.3053500

In [21]:
#Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.
import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean of each column (axis=0)
mean_vector = np.mean(data, axis=0)

# Compute the standard deviation of each column (axis=0)
std_vector = np.std(data, axis=0)

# Print the mean and standard deviation vectors
print("Mean of each column:\n", mean_vector)
print("\nStandard deviation of each column:\n", std_vector)


Mean of each column:
 [1.47191048 1.89906382 1.89683598 1.59776489 1.4436391 ]

Standard deviation of each column:
 [1.77726077 2.83924533 2.06686152 1.44438456 1.44291889]


In [23]:
#Now standardize the data matrix by 1) subtracting the mean off of each column, and 2) dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of
#the columns of normalized and print them out.
import numpy as np
import numpy.random as npr

# Create a fake dataset with 50 examples, each with 5 dimensions
data = np.exp(npr.randn(50, 5))

# Compute the mean and standard deviation of each column
mean_vector = np.mean(data, axis=0)
std_vector = np.std(data, axis=0)

# Standardize the data
normalized = (data - mean_vector) / std_vector

# Verify the normalization by computing the mean and standard deviation of the normalized data
mean_normalized = np.mean(normalized, axis=0)
std_normalized = np.std(normalized, axis=0)

# Print the normalized data, its mean, and standard deviation
print("Normalized data:\n", normalized)
print("\nMean of each column in normalized data:\n", mean_normalized)
print("\nStandard deviation of each column in normalized data:\n", std_normalized)


Normalized data:
 [[-1.13974170e+00  1.47439086e+00 -8.87478555e-02 -8.78181046e-01
  -7.76489960e-02]
 [ 1.61312547e-01 -7.33764515e-01  5.75370386e+00  1.82684859e+00
   1.88806490e+00]
 [-4.23639985e-01  1.03801610e+00 -6.54433329e-01 -6.98051287e-01
  -8.91811532e-01]
 [-5.27296495e-01  4.34023905e-01 -6.39729263e-01  4.40142171e-01
  -2.69288713e-01]
 [-4.05770632e-01  3.45125987e+00 -5.95683384e-01 -7.26035858e-01
   1.16299523e-01]
 [ 3.69634401e-02  1.98943814e-01  1.57823151e-01 -7.08593539e-01
  -8.05075075e-01]
 [-8.61093252e-01 -7.83890572e-01 -1.19219225e-01 -7.13538107e-01
  -7.69050844e-02]
 [-9.37612238e-01 -4.65058043e-02 -1.05359672e-01 -5.30293423e-01
   1.72400523e-01]
 [ 4.50831768e+00 -8.27379988e-01 -3.52129501e-01  1.73992389e-02
  -3.76123507e-01]
 [ 2.02237143e+00 -1.73952166e-01 -3.26974326e-01 -7.57336707e-01
  -6.41845194e-01]
 [ 2.21874433e+00 -7.73828105e-01 -6.81265763e-01  1.86395250e+00
   1.00197249e+00]
 [ 3.84877294e-02 -5.47618549e-01 -2.45869812e-

In [25]:
#question 3 A Vandermonde matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. So, if I have a column vector [x1, x2, . . . , xN]T , then the associated (square) Vandermonde matrix would be Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T for any N. Do it without using a loop.

In [27]:
import numpy as np

def vandermonde_matrix(N):
    # Create a column vector from 1 to N
    vector = np.arange(1, N + 1).reshape(-1, 1)  # Column vector
    
    # Create the Vandermonde matrix using broadcasting
    vandermonde = vector ** np.arange(N)  # Raise the vector to the power of each column index

    return vandermonde

# Example usage
N = 5
vander_matrix = vandermonde_matrix(N)
print(f"Vandermonde matrix for N={N}:\n", vander_matrix)


Vandermonde matrix for N=5:
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [ ]:
# question 3 () Now, let’s make a pretend linear system problem with this matrix. Create a vector
#of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector b.

In [29]:
import numpy as np

def vandermonde_matrix(N):
    # Create a column vector from 1 to N
    vector = np.arange(1, N + 1).reshape(-1, 1)  # Column vector
    
    # Create the Vandermonde matrix using broadcasting
    vandermonde = vector ** np.arange(N)  # Raise the vector to the power of each column index

    return vandermonde

# Define N for the Vandermonde matrix
N = 12
vander = vandermonde_matrix(N)

# Create a vector of all ones of length 12
x = np.ones(N)

# Perform matrix-vector multiplication
b = vander @ x  # Alternatively, you can use np.dot(vander, x)

# Print the resulting vector b
print("Vector b (result of matrix-vector multiplication):\n", b)


Vector b (result of matrix-vector multiplication):
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


In [31]:
#First, solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert V and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.
import numpy as np

def vandermonde_matrix(N):
    # Create a column vector from 1 to N
    vector = np.arange(1, N + 1).reshape(-1, 1)  # Column vector
    
    # Create the Vandermonde matrix using broadcasting
    vandermonde = vector ** np.arange(N)  # Raise the vector to the power of each column index

    return vandermonde

# Define N for the Vandermonde matrix
N = 12
vander = vandermonde_matrix(N)

# Create a vector of all ones of length 12
x = np.ones(N)

# Perform matrix-vector multiplication to get b
b = vander @ x

# Importing numpy.linalg to solve the linear system
import numpy.linalg as linalg

# Solve the linear system by inverting the Vandermonde matrix and multiplying by b
x_solution = linalg.inv(vander) @ b

# Print the result
print("Solution for x (using naive method):\n", x_solution)


Solution for x (using naive method):
 [-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


In [33]:
# question Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?
import numpy as np

def vandermonde_matrix(N):
    # Create a column vector from 1 to N
    vector = np.arange(1, N + 1).reshape(-1, 1)  # Column vector
    
    # Create the Vandermonde matrix using broadcasting
    vandermonde = vector ** np.arange(N)  # Raise the vector to the power of each column index

    return vandermonde

# Define N for the Vandermonde matrix
N = 12
vander = vandermonde_matrix(N)

# Create a vector of all ones of length 12
x = np.ones(N)

# Perform matrix-vector multiplication to get b
b = vander @ x

# Importing numpy.linalg to solve the linear system
import numpy.linalg as linalg

# Solve the linear system using numpy.linalg.solve
x_solution_solve = linalg.solve(vander, b)

# Print the result
print("Solution for x (using solve method):\n", x_solution_solve)


Solution for x (using solve method):
 [0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


In [ ]:
https://github.com/Yuv89singh/Yuvraj_singh_24_27_01.git